// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIitrAiiWKF3z-DkRgJHMAfSnRco5ojlg',
    appId: '1:308749485078:web:caa9cf20cf897840d9e137',
    messagingSenderId: '308749485078',
    projectId: 'tetugas-90d30',
    authDomain: 'tetugas-90d30.firebaseapp.com',
    storageBucket: 'tetugas-90d30.firebasestorage.app',
    measurementId: 'G-HVC111FHX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAkdmt6UqchdaEPpgFhhS_gL0lu9iV8Nk',
    appId: '1:308749485078:android:ffdb50592a38f655d9e137',
    messagingSenderId: '308749485078',
    projectId: 'tetugas-90d30',
    storageBucket: 'tetugas-90d30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeLNCML-M12HEuflgKDWZaPM7Fw3cxutk',
    appId: '1:308749485078:ios:330d28530eb8d396d9e137',
    messagingSenderId: '308749485078',
    projectId: 'tetugas-90d30',
    storageBucket: 'tetugas-90d30.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeLNCML-M12HEuflgKDWZaPM7Fw3cxutk',
    appId: '1:308749485078:ios:330d28530eb8d396d9e137',
    messagingSenderId: '308749485078',
    projectId: 'tetugas-90d30',
    storageBucket: 'tetugas-90d30.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIitrAiiWKF3z-DkRgJHMAfSnRco5ojlg',
    appId: '1:308749485078:web:e4c30167a641ba98d9e137',
    messagingSenderId: '308749485078',
    projectId: 'tetugas-90d30',
    authDomain: 'tetugas-90d30.firebaseapp.com',
    storageBucket: 'tetugas-90d30.firebasestorage.app',
    measurementId: 'G-N8RVP71KLR',
  );
}
